---
- name: Create VM and do some stuff - an ugly hack but no seemingly no multipass module exists
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Set a random hostname
    set_fact:
      r_digits: "{{ lookup('password', '/dev/null chars=digits length=3') }}"
    with_sequence: start=0 end="{{ nodes|int -1 }}"
    register: no_list



  - name: Ask Multipass to create VM, using external variable 
    ansible.builtin.shell: multipass launch --name k8s-node-{{ item.ansible_facts.r_digits }} --cloud-init files/cloud-init.yml
    with_items: "{{ no_list.results }}"
    async: 600
    poll: 0    
    register: create_vm_status



  - name: Wait for creation to finish
    async_status:
      jid: "{{ item.ansible_job_id }}"
    register: jobs
    until: jobs.finished
    delay: 3  # Check every 5 seconds. Adjust as you like.
    retries: 50  # Retry up to 10 times. Adjust as needed.
    with_items: "{{ create_vm_status.results }}"



  - name: Stop new VM
    ansible.builtin.command: "multipass stop k8s-node-{{item.ansible_facts.r_digits }}"
    with_items: "{{ no_list.results }}"



  - name: Pause for 10 secs so the next command won't fail - this could be prettier, apply some sort of when-conditional
    pause:
      seconds: 3



  - name: Fix bridge
    ansible.builtin.command: "VBoxManage modifyvm k8s-node-{{item.ansible_facts.r_digits }} --nic2 bridged --bridgeadapter2 en0"
    become: yes
    with_items: "{{ no_list.results }}"
    retries: 3
    delay: 3
    register: result
    until: result.rc == 0


  - name: Start new VM
    ansible.builtin.command: "multipass start k8s-node-{{item.ansible_facts.r_digits }}"
    become: yes
    become_user: mjau
    with_items: "{{ no_list.results }}"



  - name: Enter bridge conf
    ansible.builtin.raw:  multipass exec -- k8s-node-{{item.ansible_facts.r_digits }} sudo bash -c "cat > /etc/netplan/60-bridge.yaml" < files/bridge.conf
    with_items: "{{ no_list.results }}"

  - name: Apply bridge configuration
    ansible.builtin.command: "multipass exec k8s-node-{{item.ansible_facts.r_digits }} sudo netplan apply"
    with_items: "{{ no_list.results }}"

